import type {NextPage} from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from "../components/NavBar/NavBar";
import {
    Box,
    Button,
    ButtonGroup,
    Center,
    HStack,
    Heading,
    Image,
    Input,
    InputGroup,
    InputLeftAddon,
    InputRightAddon,
    InputRightElement,
    Show,
    SimpleGrid,
    Text,
    Link
} from '@chakra-ui/react';
import {GoSearch} from "react-icons/go";
import React, {useEffect, useState} from 'react';
import {getAllVideos} from "../lib/polybase";
import VideoGrid from "../components/VideoGrid";
import {useRouter} from "next/router";

export default function Index() {
    const [videos, setVideos] = useState<any[]>([])
    const [searchTerm, setSearchTerm] = useState("")
    const router = useRouter()
    useEffect(() => {
        getAllVideos().then(res => {
            console.log(res)
            setVideos(res.response.data)
        })
    }, [])

    const filteredVideos = videos.filter(
        (video) =>
            video?.data?.title?.toLowerCase().includes(searchTerm.toLowerCase()) ||
            video?.data?.description?.toLowerCase().includes(searchTerm.toLowerCase())
    );

    console.log("filteredVideos", filteredVideos)

    return (
        <div className={styles.container}>
            <Head>
                <title>Stream You</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon"/>
            </Head>
            <Navbar>
                <Box minH="88vh" display={"flex"} flexDirection={"column"} rowGap={"3vh"}>
                    <Center>
                        <InputGroup width={"40%"} display={"flex"} flexDirection={"row"} alignItems={"center"}>
                            <Input placeholder='Look for your Favorites!' border="1px" borderColor="telegram" type="text" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)}
                                   color="telegram.900"/>
                            <InputRightElement width='4.5rem' p={1}>
                                <Button h='100%' colorScheme='telegram'>
                                    <GoSearch/>
                                </Button>
                            </InputRightElement>
                        </InputGroup>
                    </Center>
                    <HStack justifyContent={"center"}>
                        <ButtonGroup colorScheme='linkedin'>
                            <Button>All</Button>
                            <Button>Gaming</Button>
                            <Button>Riding</Button>
                            <Button>Exotic</Button>
                            <Show breakpoint='(max-width: 900px)'>
                                <Button>Interesting</Button>
                                <Button>Books</Button>
                                <Button>Astronomy</Button>
                                <Button>Live</Button>
                                <Button>Animated</Button>
                                <Button>Comedy</Button>
                                <Button>Anime</Button>
                                <Button>All</Button>
                                <Button>Gaming</Button>
                                <Button>Riding</Button>
                            </Show>
                        </ButtonGroup>
                    </HStack>
                    {
                        videos && <Center
                        width={"100%"} mx={2}
                        ><SimpleGrid p={4} columns={3} spacing={10} width={"100%"}>
                            {
                                filteredVideos?.map((video, index) => {
                                    return (
                                        <Box display={"flex"} flexDirection={"column"} w="18vw" key={index}
                                             backgroundColor={"whiteAlpha.600"} borderRadius={"20"} cursor={"pointer"}
                                             onClick={() => router.push(`/app/watchstream?video=${video?.data.id}`)}>
                                            <Image
                                                src={video?.data.thumbnail}
                                                borderRadius={"20px"} height={300}/>
                                            <Heading p={2} size={"md"}>{video.data.title || "Loading..."}</Heading>
                                            <Link href={`/app/creator?channelId=${video?.data.channelId}`} size={"sm"}
                                                  color={"dimgrey"} px={2}>Creator</Link>
                                            <Text p={2}
                                                  color={"dimgray"}>{`${video?.data.description?.slice(0, 15)}...`}</Text>
                                        </Box>
                                    )
                                })
                            }
                        </SimpleGrid>
                        </Center>
                    }
                </Box>
            </Navbar>
        </div>
    );
};
