import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {

    /*
    const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        console.log(name);
        const file = jsonToFile({name}, "name.json");
        const res = await uploadSpheron(file)
        console.log({res});
    }
    */

  return (
    <div className={styles.container}>
      <Head>
        <title>Stream You</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
    </div>
  );
};

export default Home;
